version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - "type: dependencies"
  ignore:
  - dependency-name: "@hapi/joi"
    versions:
    - ">= 16.a"
    - "< 18"
  - dependency-name: "@types/hapi__joi"
    versions:
    - ">= 16.a"
    - "< 18"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
