#########################################
#    Only used for (smoke) tests,       #
# not the actual release drafter action #
#########################################

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: 'Breaking'
    semver-increment: 'major'
    exclusive: true
    when:
      conventional:
        breaking: true
  - title: 'New'
    semver-increment: 'minor'
    exclusive: true
    when:
      conventional:
        type: 'feat'
  - title: 'Dependency Updates'
    semver-increment: 'patch'
    exclusive: true
    when:
      conventional:
        scopes:
          - 'deps'
          - 'deps-dev'
        types:
          - 'build'
          - 'chore'
          - 'ci'
          - 'fix'
    collapse-after: 5
  - title: 'Bug Fixes'
    semver-increment: 'patch'
    exclusive: true
    when:
      conventional:
        type: 'fix'
  - title: 'Maintenance'
    semver-increment: 'patch'
    exclusive: true
    when:
      conventional:
        types:
          - 'build'
          - 'chore'
          - 'ci'
          - 'perf'
          - 'refactor'
          - 'revert'
          - 'style'
          - 'test'
  - title: 'Documentation'
    semver-increment: 'patch'
    exclusive: true
    when:
      conventional:
        type: 'docs'
  - title: 'Other changes'
  - type: 'pre-exclude'
    when:
      label: 'skip-changelog'
