# yaml-language-server: $schema=../schema.json
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: 'Breaking'
    labels:
      - 'type: breaking'
  - title: 'New'
    labels:
      - 'type: feature'
  - title: 'Bug Fixes'
    labels:
      - 'type: bug'
  - title: 'Maintenance'
    labels:
      - 'type: maintenance'
  - title: 'Documentation'
    labels:
      - 'type: docs'
  - title: 'Other changes'
  - title: 'Dependency Updates'
    labels:
      - 'type: dependencies'
    collapse-after: 5

no-changes-template: '* No changes'

version-resolver:
  major:
    labels:
      - 'type: breaking'
  minor:
    labels:
      - 'type: feature'
  patch:
    labels:
      - 'type: bug'
      - 'type: maintenance'
      - 'type: docs'
      - 'type: dependencies'
      - 'type: security'

exclude-labels:
  - 'skip-changelog'
