name: Node & npm setup
author: Clément Chanchevrier @cchanche
description: 'Common job setup for npm managed repo'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 20

    - name: Install dependencies
      shell: bash
      run: npm ci
