name: 'Release Drafter'
description: 'Drafts your next release notes as pull requests are merged into master.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: edit-2
  color: orange
