query resolveCommitish($name: String!, $owner: String!, $expression: String!) {
  repository(name: $name, owner: $owner) {
    object(expression: $expression) {
      __typename
      oid
    }
  }
}

query resolvePullRequestCommitish(
  $name: String!
  $owner: String!
  $number: Int!
) {
  repository(name: $name, owner: $owner) {
    pullRequest(number: $number) {
      headRefOid
      mergeCommit {
        oid
      }
      potentialMergeCommit {
        oid
      }
    }
  }
}
