import { MajorMinorPatch, SORT_BY, SORT_DIRECTIONS } from './enums.js'
import { ReleaseDrafterConfig } from './types.js'

export const DEFAULT_CONFIG: ReleaseDrafterConfig = Object.freeze({
	autolabeler: [],
	categories: [],
	categoryTemplate: `## $TITLE`,
	changeTemplate: `* $TITLE (#$NUMBER) @$AUTHOR`,
	changeTitleEscapes: '',
	commitish: '',
	excludeContributors: [],
	excludeLabels: [],
	filterByCommitish: false,
	footer: '',
	header: '',
	includeLabels: [],
	includePaths: [],
	nameTemplate: '',
	noChangesTemplate: `* No changes`,
	noContributorsTemplate: 'No contributors',
	prerelease: false,
	references: ['main'],
	replacers: [],
	sortBy: SORT_BY.mergedAt,
	sortDirection: SORT_DIRECTIONS.descending,
	tagPrefix: '',
	tagTemplate: 'v$RESOLVED_VERSION',
	template: `## What’s Changed\n\n$CHANGES`,
	versionTemplate: `$MAJOR.$MINOR.$PATCH`,
	versionResolver: {
		major: { labels: [] },
		minor: { labels: [] },
		patch: { labels: [] },
		default: MajorMinorPatch.patch,
	},
})
