query findCommitsWithPathChangesQuery(
  $name: String!
  $owner: String!
  $targetCommitish: String!
  $after: String
  $path: String
) {
  repository(name: $name, owner: $owner) {
    object(expression: $targetCommitish) {
      ... on Commit {
        __typename
        history(path: $path, after: $after) {
          __typename
          pageInfo {
            __typename
            hasNextPage
            endCursor
          }
          nodes {
            __typename
            id
          }
        }
      }
    }
  }
}
