name: 'Release Drafter - Auto Labeler'
description: 'Automatically labels pull requests based on your configuration.'
author: release-drafter
branding:
  icon: edit-2
  color: orange
runs:
  using: node24
  main: ../dist/actions/autolabeler/run.js
inputs:
  token:
    description: >
      Access token used to make requests against the GitHub API. Defaults to
      github.token.
    default: ${{ github.token }}
  config-name:
    description: |
      If your workflow requires multiple autolabeler configs it can be helpful to override the config-name.
      The config should still be located inside `.github` as that's where we are looking for config files.
    required: false
    default: 'release-drafter.yml'

outputs: {}
