#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Issue https://github.com/okonet/lint-staged/issues/1164
# Workaround https://github.com/typicode/husky/issues/968#issuecomment-1176848345
if [ -t 2 ]; then
  exec >/dev/tty 2>&1
fi

[ ! -x "$(command -v npx)" ] || npx lint-staged
