name: Continuous Integration

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - uses: ./.github/actions/common-setup

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Type checks
        id: npm-ts-checks
        run: npm run tsc:check

      - name: Tests
        id: npm-ci-test
        run: npm run test:run
