name: Release

on:
  push:
    tags:
      - v*.*.*

permissions:
  id-token: write
  contents: write

jobs:
  build:
    if: github.repository == 'release-drafter/release-drafter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: .node-version
          cache: npm

      - run: npm ci

      - name: Run all checks and rebuild artifacts
        run: npm run all

      - name: Check for clean working directory
        run: npm run check:clean

      - name: Publish
        if: false # Publishing is currently disabled, see https://github.com/release-drafter/release-drafter/pull/1475#discussion_r2901869066
        run: npm publish # Publishes to npmjs, using package.json's version

      - name: Parse pushed tag version
        id: version
        run: |
          tag=${GITHUB_REF/refs\/tags\//}
          version=${tag#v}
          major=${version%%.*}
          echo "tag=${tag}" >> $GITHUB_OUTPUT
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "major=${major}" >> $GITHUB_OUTPUT

      - name: Publish Release
        uses: release-drafter/release-drafter@0c2e5e9262c9adee6ef5b8631aaa5e374e277d76 # master
        with:
          version: ${{ steps.version.outputs.version }}
          publish: true

      - name: Update major tag v${{ steps.version.outputs.major }}
        run: |
          git tag v${{ steps.version.outputs.major }} ${{ steps.version.outputs.tag }} -f
          git push origin refs/tags/v${{ steps.version.outputs.major }} -f
