name: Release

on:
  push:
    tags:
      - v*.*.*

permissions:
  id-token: write
  contents: write

jobs:
  build:
    if: github.repository == 'release-drafter/release-drafter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ./.github/actions/common-setup

      - uses: ./.github/actions/continuous-integration

      - name: Publish
        if: false # Publishing is currently disabled, see https://github.com/release-drafter/release-drafter/pull/1475#discussion_r2901869066
        run: npm publish # Publishes to npmjs, using package.json's version

      - name: Parse pushed tag version
        id: version
        run: |
          tag=${GITHUB_REF/refs\/tags\//}
          version=${tag#v}
          major=${version%%.*}
          echo "tag=${tag}" >> $GITHUB_OUTPUT
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "major=${major}" >> $GITHUB_OUTPUT

      - name: Publish Release
        uses: release-drafter/release-drafter@master
        with:
          version: ${{ steps.version.outputs.version }}
          publish: true

      - name: Update major tag v${{ steps.version.outputs.major }}
        run: |
          git tag v${{ steps.version.outputs.major }} ${{ steps.version.outputs.tag }} -f
          git push origin refs/tags/v${{ steps.version.outputs.major }} -f
