name: Renovate Build

on:
  push:
    branches:
      - renovate/**

permissions:
  contents: write

jobs:
  build:
    name: Rebuild artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: .node-version
          cache: npm

      - run: npm ci

      - name: Run all checks and rebuild artifacts
        run: npm run all

      - name: Commit updated artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
              git add dist/ \
              badges/coverage.svg \
              schema.json \
              autolabeler/schema.json \
              drafter/schema.json
            git commit -m "chore(build): rebuild artifacts"
            git push
          else
            echo "No changes to commit"
          fi

      - name: Check for clean working directory
        run: npm run check:clean
